"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 21:55:01.901861
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_accounts_name'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_created_at'), ['created_at'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=False),
    sa.Column('escalation_rules', sa.JSON(), nullable=False),
    sa.Column('default_tier', sa.Enum('FAST', 'BALANCED', 'DEEP', name='modeltier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('performance_measures', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active_config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("default_tier IN ('FAST', 'BALANCED', 'DEEP')", name='modeltier'),
    sa.CheckConstraint("default_tier IN ('FAST', 'BALANCED', 'DEEP')", name=op.f('ck_agents_modeltier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_created_at'), ['created_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('who', sa.String(length=64), nullable=False),
    sa.Column('what', sa.String(length=120), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_log_hash'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_what'), ['what'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_who'), ['who'], unique=False)

    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('customers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_created_at'), ['created_at'], unique=False)

    op.create_table('cost_centers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_centers')),
    sa.UniqueConstraint('name', name=op.f('uq_cost_centers_name'))
    )
    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_centers_created_at'), ['created_at'], unique=False)

    op.create_table('events',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('forecasts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('FORECAST', 'ESTIMATE', name='forecastkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('FORECAST', 'ESTIMATE')", name='forecastkind'),
    sa.CheckConstraint("kind IN ('FORECAST', 'ESTIMATE')", name=op.f('ck_forecasts_forecastkind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_created_at'), ['created_at'], unique=False)

    op.create_table('founders',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_founders'))
    )
    with op.batch_alter_table('founders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founders_created_at'), ['created_at'], unique=False)

    op.create_table('metrics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_agent', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_metrics'))
    )
    op.create_table('sources',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_key', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_date', sa.String(length=64), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('credibility', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='credibility', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("credibility IN ('HIGH', 'MEDIUM', 'LOW')", name='credibility'),
    sa.CheckConstraint("credibility IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_sources_credibility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('url_key', name=op.f('uq_sources_url_key'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_created_at'), ['created_at'], unique=False)

    op.create_table('system_configuration',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_configuration'))
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_ai_provider', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('name', name=op.f('uq_vendors_name'))
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_created_at'), ['created_at'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL', name='runstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('understanding', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('total_cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('budget_limit_micros', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL')", name='runstatus'),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL')", name=op.f('ck_workflow_runs_runstatus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_command'), ['command'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)

    op.create_table('audits',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('verdict', sa.Enum('PASS', 'PASS_WITH_CONDITIONS', 'REVIEW_REQUIRED', 'BLOCK', name='auditverdict', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=True),
    sa.Column('auditor', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("verdict IN ('PASS', 'PASS_WITH_CONDITIONS', 'REVIEW_REQUIRED', 'BLOCK')", name='auditverdict'),
    sa.CheckConstraint("verdict IN ('PASS', 'PASS_WITH_CONDITIONS', 'REVIEW_REQUIRED', 'BLOCK')", name=op.f('ck_audits_auditverdict')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_audits_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audits'))
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('budgets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('cost_center_id', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_budgets_cost_center_id_cost_centers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_created_at'), ['created_at'], unique=False)

    op.create_table('decisions',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('final_decision', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('outcome_assessment', sa.String(length=32), nullable=True),
    sa.Column('outcome_why', sa.Text(), nullable=True),
    sa.Column('decision_maker', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='decisionstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reversibility', sa.String(length=32), nullable=True),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED')", name='decisionstatus'),
    sa.CheckConstraint("status IN ('PROPOSED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED')", name=op.f('ck_decisions_decisionstatus')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_decisions_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('goals',
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('horizon', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_goals_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_created_at'), ['created_at'], unique=False)

    op.create_table('import_batches',
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('imported_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_import_batches_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_created_at'), ['created_at'], unique=False)

    op.create_table('memories',
    sa.Column('founder_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.Enum('FOUNDER', 'COMPANY', 'PROJECT', 'RESEARCH', 'DECISION', 'FINANCIAL', 'AGENT', 'SYSTEM', name='memorycategory', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('EXPLICIT', 'CONFIRMED', 'INFERRED', 'HYPOTHESIS', 'SUPERSEDED', name='memorystatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provenance', sa.Enum('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT', name='provenance', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=32), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('FOUNDER', 'COMPANY', 'PROJECT', 'RESEARCH', 'DECISION', 'FINANCIAL', 'AGENT', 'SYSTEM')", name='memorycategory'),
    sa.CheckConstraint("category IN ('FOUNDER', 'COMPANY', 'PROJECT', 'RESEARCH', 'DECISION', 'FINANCIAL', 'AGENT', 'SYSTEM')", name=op.f('ck_memories_memorycategory')),
    sa.CheckConstraint("provenance IN ('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT')", name='provenance'),
    sa.CheckConstraint("provenance IN ('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT')", name=op.f('ck_memories_provenance')),
    sa.CheckConstraint("status IN ('EXPLICIT', 'CONFIRMED', 'INFERRED', 'HYPOTHESIS', 'SUPERSEDED')", name='memorystatus'),
    sa.CheckConstraint("status IN ('EXPLICIT', 'CONFIRMED', 'INFERRED', 'HYPOTHESIS', 'SUPERSEDED')", name=op.f('ck_memories_memorystatus')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_memories_confidence_range')),
    sa.ForeignKeyConstraint(['founder_id'], ['founders.id'], name=op.f('fk_memories_founder_id_founders')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['memories.id'], name=op.f('fk_memories_superseded_by_id_memories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index('ix_memories_active', ['category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_founder_id'), ['founder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_subject'), ['subject'], unique=False)

    op.create_table('subscriptions',
    sa.Column('vendor_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('last_charge_date', sa.Date(), nullable=True),
    sa.Column('next_charge_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_subscriptions_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('approvals',
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Enum('SPEND', 'COMMUNICATE', 'DELETE', 'PRODUCTION_CHANGE', 'SYSTEM_CHANGE', 'PUBLISH', 'CONTRACT', 'DECISION', 'PLAN', name='approvaltype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('approver', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action_type IN ('SPEND', 'COMMUNICATE', 'DELETE', 'PRODUCTION_CHANGE', 'SYSTEM_CHANGE', 'PUBLISH', 'CONTRACT', 'DECISION', 'PLAN')", name='approvaltype'),
    sa.CheckConstraint("action_type IN ('SPEND', 'COMMUNICATE', 'DELETE', 'PRODUCTION_CHANGE', 'SYSTEM_CHANGE', 'PUBLISH', 'CONTRACT', 'DECISION', 'PLAN')", name=op.f('ck_approvals_approvaltype')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')", name='approvalstatus'),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')", name=op.f('ck_approvals_approvalstatus')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_approvals_decision_id_decisions')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_approvals_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('decision_options',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=False),
    sa.Column('cons', sa.JSON(), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_options_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_options'))
    )
    with op.batch_alter_table('decision_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_options_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_options_decision_id'), ['decision_id'], unique=False)

    op.create_table('memory_evidence',
    sa.Column('memory_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('SUPPORTS','CONTRADICTS')", name=op.f('ck_memory_evidence_kind')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_memory_evidence_decision_id_decisions')),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_evidence_memory_id_memories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_evidence'))
    )
    with op.batch_alter_table('memory_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_evidence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_evidence_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_evidence_memory_id'), ['memory_id'], unique=False)

    op.create_table('objectives',
    sa.Column('goal_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('metric', sa.String(length=300), nullable=True),
    sa.Column('target', sa.String(length=300), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_objectives_decision_id_decisions')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_objectives_goal_id_goals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objectives'))
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectives_goal_id'), ['goal_id'], unique=False)

    op.create_table('transactions',
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('category_source', sa.String(length=16), nullable=False),
    sa.Column('is_revenue', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=True),
    sa.Column('cost_center_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTUAL', 'PENDING', 'COMMITTED', name='txnstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT', name='provenance', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('import_batch_id', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT')", name='provenance'),
    sa.CheckConstraint("source IN ('FOUNDER', 'INTERNAL_DATABASE', 'AGENT_INFERENCE', 'EXTERNAL_RESEARCH', 'FINANCIAL_IMPORT', 'TOOL_OUTPUT', 'SYSTEM_OBSERVATION', 'OTHER_AGENT')", name=op.f('ck_transactions_provenance')),
    sa.CheckConstraint("status IN ('ACTUAL', 'PENDING', 'COMMITTED')", name='txnstatus'),
    sa.CheckConstraint("status IN ('ACTUAL', 'PENDING', 'COMMITTED')", name=op.f('ck_transactions_txnstatus')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_transactions_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_transactions_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_transactions_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('dedupe_hash', name=op.f('uq_transactions_dedupe_hash'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_revenue'), ['is_revenue'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_date'), ['txn_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('agent_config_versions',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_improvement', sa.Text(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('rollback_to_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_config_versions_agent_id_agents')),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_agent_config_versions_approval_id_approvals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_config_versions')),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_version')
    )
    with op.batch_alter_table('agent_config_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_config_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_config_versions_created_at'), ['created_at'], unique=False)

    op.create_table('improvements',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('cost', sa.Text(), nullable=False),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('test_plan', sa.Text(), nullable=False),
    sa.Column('rollback', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=True),
    sa.Column('change_spec', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'TESTING', 'TESTED', 'APPROVED', 'IMPLEMENTED', 'VERIFIED', 'REJECTED', 'ROLLED_BACK', name='improvementstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=True),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'TESTING', 'TESTED', 'APPROVED', 'IMPLEMENTED', 'VERIFIED', 'REJECTED', 'ROLLED_BACK')", name='improvementstatus'),
    sa.CheckConstraint("status IN ('PROPOSED', 'TESTING', 'TESTED', 'APPROVED', 'IMPLEMENTED', 'VERIFIED', 'REJECTED', 'ROLLED_BACK')", name=op.f('ck_improvements_improvementstatus')),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_improvements_approval_id_approvals')),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], name=op.f('fk_improvements_audit_id_audits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_improvements'))
    )
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvements_status'), ['status'], unique=False)

    op.create_table('initiatives',
    sa.Column('objective_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('fk_initiatives_objective_id_objectives')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiatives'))
    )
    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_initiatives_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_initiatives_objective_id'), ['objective_id'], unique=False)

    op.create_table('experiments',
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('variant_a', sa.JSON(), nullable=False),
    sa.Column('variant_b', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('improvement_id', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvements.id'], name=op.f('fk_experiments_improvement_id_improvements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_created_at'), ['created_at'], unique=False)

    op.create_table('projects',
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('objective_id', sa.String(length=32), nullable=True),
    sa.Column('initiative_id', sa.String(length=32), nullable=True),
    sa.Column('decision_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACTIVE', 'BLOCKED', 'PAUSED', 'COMPLETED', 'CANCELLED', name='projectstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expected_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('estimated_effort_hours', sa.Float(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('blockers', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('related_research_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'ACTIVE', 'BLOCKED', 'PAUSED', 'COMPLETED', 'CANCELLED')", name='projectstatus'),
    sa.CheckConstraint("status IN ('PROPOSED', 'ACTIVE', 'BLOCKED', 'PAUSED', 'COMPLETED', 'CANCELLED')", name=op.f('ck_projects_projectstatus')),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name=op.f('ck_projects_priority_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_projects_company_id_companies')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_projects_decision_id_decisions')),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_projects_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('fk_projects_objective_id_objectives')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_initiative_id'), ['initiative_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_objective_id'), ['objective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('evaluations',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('benchmark', sa.String(length=120), nullable=False),
    sa.Column('case_id', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_evaluations_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_model'), ['model'], unique=False)

    op.create_table('milestones',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('project_dependencies',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('depends_on_id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('project_id <> depends_on_id', name=op.f('ck_project_dependencies_no_self')),
    sa.ForeignKeyConstraint(['depends_on_id'], ['projects.id'], name=op.f('fk_project_dependencies_depends_on_id_projects')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_dependencies_project_id_projects')),
    sa.PrimaryKeyConstraint('project_id', 'depends_on_id', name=op.f('pk_project_dependencies'))
    )
    op.create_table('research_reports',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_key', sa.String(length=300), nullable=False),
    sa.Column('decision_supported', sa.Text(), nullable=True),
    sa.Column('subquestions', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('disagreements', sa.JSON(), nullable=False),
    sa.Column('what_would_change', sa.JSON(), nullable=False),
    sa.Column('live_search_used', sa.Boolean(), nullable=False),
    sa.Column('freshness_days', sa.Integer(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_agent', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name='confidence'),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_research_reports_confidence')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_research_reports_company_id_companies')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_reports_project_id_projects')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_research_reports_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports'))
    )
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_reports_question_key'), ['question_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_reports_stale'), ['stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_reports_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('claims',
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_fact', sa.Boolean(), nullable=False),
    sa.Column('cited_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name='confidence'),
    sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_claims_confidence')),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], name=op.f('fk_claims_report_id_research_reports')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_claims_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_source_id'), ['source_id'], unique=False)

    op.create_table('tasks',
    sa.Column('kind', sa.Enum('PLAN', 'WORK', name='taskkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('milestone_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('responsible_agent', sa.String(length=64), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'PLANNED', 'WAITING', 'APPROVAL_REQUIRED', 'READY', 'RUNNING', 'BLOCKED', 'FAILED', 'COMPLETED', 'CANCELLED', name='taskstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('actual_cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('estimated_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('actual_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.Column('criteria_met', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_effort_hours', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind <> 'PLAN' OR status <> 'COMPLETED' OR criteria_met = 1", name=op.f('ck_tasks_completed_needs_criteria')),
    sa.CheckConstraint("kind IN ('PLAN', 'WORK')", name='taskkind'),
    sa.CheckConstraint("kind IN ('PLAN', 'WORK')", name=op.f('ck_tasks_taskkind')),
    sa.CheckConstraint("status IN ('PROPOSED', 'PLANNED', 'WAITING', 'APPROVAL_REQUIRED', 'READY', 'RUNNING', 'BLOCKED', 'FAILED', 'COMPLETED', 'CANCELLED')", name='taskstatus'),
    sa.CheckConstraint("status IN ('PROPOSED', 'PLANNED', 'WAITING', 'APPROVAL_REQUIRED', 'READY', 'RUNNING', 'BLOCKED', 'FAILED', 'COMPLETED', 'CANCELLED')", name=op.f('ck_tasks_taskstatus')),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name=op.f('ck_tasks_priority_range')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_tasks_milestone_id_milestones')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_tasks_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL', name='runstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL')", name='runstatus'),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'AWAITING_APPROVAL')", name=op.f('ck_agent_runs_runstatus')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_runs_agent_id_agents')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_agent_runs_task_id_tasks')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_agent_runs_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('depends_on_id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_id', name=op.f('ck_task_dependencies_no_self')),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_id_tasks')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id', name=op.f('pk_task_dependencies'))
    )
    op.create_table('model_usage',
    sa.Column('agent_run_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('workflow', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('web_search_requests', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('actual_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('pricing_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_usage_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_model_usage_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_usage'))
    )
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_workflow'), ['workflow'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_tool_calls_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_tool_calls_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_workflow_run_id'), ['workflow_run_id'], unique=False)

    # ### end Alembic commands ###

    # Append-only audit log: the database itself rejects UPDATE and DELETE.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute(
            "CREATE TRIGGER audit_log_no_update BEFORE UPDATE ON audit_log "
            "BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;"
        )
        op.execute(
            "CREATE TRIGGER audit_log_no_delete BEFORE DELETE ON audit_log "
            "BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;"
        )
    elif bind.dialect.name == "postgresql":
        op.execute(
            "CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'audit_log is append-only'; END; $$ LANGUAGE plpgsql;"
        )
        op.execute(
            "CREATE TRIGGER audit_log_no_mutation BEFORE UPDATE OR DELETE ON audit_log "
            "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update")
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete")
    elif bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_mutation ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_agent_run_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('model_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_workflow'))
        batch_op.drop_index(batch_op.f('ix_model_usage_model'))
        batch_op.drop_index(batch_op.f('ix_model_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_usage_agent_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_agent_id'))

    op.drop_table('model_usage')
    op.drop_table('task_dependencies')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_kind'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_source_id'))
        batch_op.drop_index(batch_op.f('ix_claims_report_id'))
        batch_op.drop_index(batch_op.f('ix_claims_created_at'))

    op.drop_table('claims')
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_reports_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_reports_stale'))
        batch_op.drop_index(batch_op.f('ix_research_reports_question_key'))
        batch_op.drop_index(batch_op.f('ix_research_reports_created_at'))

    op.drop_table('research_reports')
    op.drop_table('project_dependencies')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_created_at'))

    op.drop_table('milestones')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_model'))
        batch_op.drop_index(batch_op.f('ix_evaluations_created_at'))
        batch_op.drop_index(batch_op.f('ix_evaluations_agent_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_objective_id'))
        batch_op.drop_index(batch_op.f('ix_projects_initiative_id'))
        batch_op.drop_index(batch_op.f('ix_projects_decision_id'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))
        batch_op.drop_index(batch_op.f('ix_projects_company_id'))

    op.drop_table('projects')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_created_at'))

    op.drop_table('experiments')
    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_initiatives_objective_id'))
        batch_op.drop_index(batch_op.f('ix_initiatives_created_at'))

    op.drop_table('initiatives')
    with op.batch_alter_table('improvements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvements_status'))
        batch_op.drop_index(batch_op.f('ix_improvements_created_at'))

    op.drop_table('improvements')
    with op.batch_alter_table('agent_config_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_config_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_config_versions_agent_id'))

    op.drop_table('agent_config_versions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_txn_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_revenue'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_goal_id'))
        batch_op.drop_index(batch_op.f('ix_objectives_created_at'))

    op.drop_table('objectives')
    with op.batch_alter_table('memory_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_evidence_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_evidence_decision_id'))
        batch_op.drop_index(batch_op.f('ix_memory_evidence_created_at'))

    op.drop_table('memory_evidence')
    with op.batch_alter_table('decision_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_options_decision_id'))
        batch_op.drop_index(batch_op.f('ix_decision_options_created_at'))

    op.drop_table('decision_options')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_decision_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_created_at'))
        batch_op.drop_index(batch_op.f('ix_approvals_action_type'))

    op.drop_table('approvals')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_subject'))
        batch_op.drop_index(batch_op.f('ix_memories_status'))
        batch_op.drop_index(batch_op.f('ix_memories_founder_id'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))
        batch_op.drop_index(batch_op.f('ix_memories_category'))
        batch_op.drop_index('ix_memories_active')

    op.drop_table('memories')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_created_at'))

    op.drop_table('import_batches')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_created_at'))
        batch_op.drop_index(batch_op.f('ix_goals_company_id'))

    op.drop_table('goals')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_created_at'))

    op.drop_table('budgets')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_audits_created_at'))

    op.drop_table('audits')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_decision_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_command'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_created_at'))

    op.drop_table('vendors')
    op.drop_table('system_configuration')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_created_at'))

    op.drop_table('sources')
    op.drop_table('metrics')
    with op.batch_alter_table('founders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founders_created_at'))

    op.drop_table('founders')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_created_at'))

    op.drop_table('forecasts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_centers_created_at'))

    op.drop_table('cost_centers')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_created_at'))

    op.drop_table('companies')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_who'))
        batch_op.drop_index(batch_op.f('ix_audit_log_what'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_created_at'))

    op.drop_table('agents')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_created_at'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
