"""media assets

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 11:15:50.806481
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('kind', sa.Enum('VOICE_REFERENCE', 'AVATAR_SOURCE', 'VOICE_AUDIO', 'AVATAR_VIDEO', name='mediakind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', 'DRAFT', 'FAILED', name='mediastatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('engine', sa.String(length=120), nullable=True),
    sa.Column('parent_ids', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('VOICE_REFERENCE', 'AVATAR_SOURCE', 'VOICE_AUDIO', 'AVATAR_VIDEO')", name='mediakind'),
    sa.CheckConstraint("kind IN ('VOICE_REFERENCE', 'AVATAR_SOURCE', 'VOICE_AUDIO', 'AVATAR_VIDEO')", name=op.f('ck_media_assets_mediakind')),
    sa.CheckConstraint("status IN ('ACTIVE', 'RETIRED', 'DRAFT', 'FAILED')", name='mediastatus'),
    sa.CheckConstraint("status IN ('ACTIVE', 'RETIRED', 'DRAFT', 'FAILED')", name=op.f('ck_media_assets_mediastatus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_status'))
        batch_op.drop_index(batch_op.f('ix_media_assets_kind'))
        batch_op.drop_index(batch_op.f('ix_media_assets_created_at'))

    op.drop_table('media_assets')
    # ### end Alembic commands ###
